openapi: 3.0.0
info:
  title: express-mongo-crud-api
  version: 1.0.0
  description: A study project demonstrating the use of Node.js, Express, and TypeScript to build a RESTful API

servers:
  - url: http://localhost:3200/

tags:
  - name: Clients
  - name: Products
  - name: Orders

paths:
  /api/v1/clients:
    get:
      summary: Retrieve all clients
      tags: [Clients]
      responses:
        200:
          description: A list with all clients available
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Client"

    post:
      summary: Create a new client
      tags: [Clients]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Client"
      responses:
        201:
          description: Client successfully created

  /api/v1/clients/{clientId}:
    get:
      summary: Retrieve a specific client
      tags: [Clients]
      parameters:
        - $ref: "#/components/parameters/ClientId"
      responses:
        200:
          description: Client details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Client"

    put:
      summary: Update a specific client
      tags: [Clients]
      parameters:
        - $ref: "#/components/parameters/ClientId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Client"
      responses:
        200:
          description: Client updated successfully

    delete:
      summary: Delete a specific client
      tags: [Clients]
      parameters:
        - $ref: "#/components/parameters/ClientId"
      responses:
        204:
          description: Client successfully deleted

  /api/v1/products:
    get:
      summary: Retrieve all products
      tags: [Products]
      responses:
        200:
          description: A list with all products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
    post:
      summary: Create a new product
      tags: [Products]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        201:
          description: Product successfully created

  /api/v1/products/{productId}:
    get:
      summary: Get a specific product
      tags: [Products]
      parameters:
        - $ref: "#/components/parameters/ProductId"
      responses:
        200:
          description: Product details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
    put:
      summary: Update a specific product
      tags: [Products]
      parameters:
        - $ref: "#/components/parameters/ProductId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        200:
          description: Product updated
    delete:
      summary: Delete a specific product
      tags: [Products]
      parameters:
        - $ref: "#/components/parameters/ProductId"
      responses:
        204:
          description: Product deleted

  /api/v1/orders:
    get:
      summary: Retrieve all orders
      tags: [Orders]
      responses:
        200:
          description: A list with all orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
    post:
      summary: Create a new order
      tags: [Orders]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        201:
          description: Order created

  /api/v1/orders/{orderId}:
    get:
      summary: Get a specific order
      tags: [Orders]
      parameters:
        - $ref: "#/components/parameters/OrderId"
      responses:
        200:
          description: Order details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
    put:
      summary: Update a specific order
      tags: [Orders]
      parameters:
        - $ref: "#/components/parameters/OrderId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        200:
          description: Order updated
    delete:
      summary: Delete a specific order
      tags: [Orders]
      parameters:
        - $ref: "#/components/parameters/OrderId"
      responses:
        204:
          description: Order deleted

components:
  parameters:
    ClientId:
      name: clientId
      in: path
      required: true
      description: The ID of the client
      schema:
        type: string
    ProductId:
      name: productId
      in: path
      required: true
      description: The ID of the product
      schema:
        type: string
    OrderId:
      name: orderId
      in: path
      required: true
      description: The ID of the order
      schema:
        type: string

  schemas:
    Client:
      type: object
      required:
        - firstName
        - lastName
        - phone
        - email
      properties:
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        email:
          type: string
          format: email
          example: john.doe@example.com
        phone:
          type: string
          example: "+1-555-555-5555"
          pattern: "^(\\+?1?[-.\\s]?(\\([2-9]\\d{2}\\)|[2-9]\\d{2})[-.\\s]?\\d{3}[-.\\s]?\\d{4})$"
          description: Must be a valid North American phone number
    Product:
      type: object
      required:
        - name
        - price
      properties:
        name:
          type: string
          example: Coffee Mug
        description:
          type: string
          example: A stylish ceramic coffee mug
        price:
          type: number
          example: 14.99
        stock:
          type: integer
          example: 50
    Order:
      type: object
      required:
        - client
        - products
        - totalPrice
      properties:
        client:
          type: string
          description: ID of the client
          example: 123e4567-e89b-12d3-a456-426614174000
        products:
          type: array
          items:
            type: object
            properties:
              product:
                type: string
                example: 60d21b4667d0d8992e610c85
              quantity:
                type: integer
                example: 2
        totalPrice:
          type: number
          example: 26.98
        status:
          type: string
          enum: [pending, completed, cancelled]
          example: pending
